"""
Django settings for LMS project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import logging
import cloudinary
import cloudinary.uploader
import cloudinary.api
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


logger = logging.getLogger(__name__)


def _csv_env(name, default):
    raw_value = config(name, default=default)
    if isinstance(raw_value, (list, tuple)):
        return [item for item in raw_value if item]
    return [item.strip() for item in str(raw_value).split(',') if item.strip()]


def _require_production_value(name, value):
    if IS_PRODUCTION and not value:
        raise RuntimeError(f"{name} must be set when DJANGO_ENV=production")
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = "django-insecure-fcsqu(78i@7a^!hp@fh$$wb7zbpzo5r2+ev%cl(c5me(uhr5f2"

DJANGO_ENV = config("DJANGO_ENV", default=config("ENVIRONMENT", default="development")).lower()
IS_PRODUCTION = DJANGO_ENV in {"production", "prod"}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=not IS_PRODUCTION, cast=bool)

ALLOWED_HOSTS = _csv_env(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,0.0.0.0,[::1],.onrender.com,lms-backend-eff3.onrender.com",
)
_require_production_value("ALLOWED_HOSTS", ALLOWED_HOSTS)

FRONTEND_BASE_URL = config("FRONTEND_BASE_URL", default="http://127.0.0.1:3000")
API_BASE_URL = config("API_BASE_URL", default="http://127.0.0.1:8000")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    # 'debug_toolbar',
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
    "accounts",
    "courses",
    "events",
    "badges",
    'cloudinary_storage',
    'cloudinary',
]

# --- Configure Cloudinary Credentials ---
cloudinary.config(
    cloud_name=config('CLOUDINARY_CLOUD_NAME'),
    api_key=config('CLOUDINARY_API_KEY'),
    api_secret=config('CLOUDINARY_API_SECRET')
)


SCORM_CLOUD_APP_ID = config('SCORM_CLOUD_APP_ID')
SCORM_CLOUD_SECRET_KEY = config('SCORM_CLOUD_SECRET_KEY')
SCORM_CLOUD_BASE_URL = config('SCORM_CLOUD_BASE_URL')
SCORM_POSTBACK_SECRET = config('SCORM_POSTBACK_SECRET', default='' if not IS_PRODUCTION else '')

_require_production_value("SCORM_POSTBACK_SECRET", SCORM_POSTBACK_SECRET)

# --- Set Cloudinary as the Default Storage ---
# This means ALL your FileField/ImageField uploads will go to Cloudinary.
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage' # For user-uploaded media[reference:5]
STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'

CORS_ALLOWED_ORIGINS = _csv_env(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,https://skillbridge-eight-iota.vercel.app",
)
_require_production_value("CORS_ALLOWED_ORIGINS", CORS_ALLOWED_ORIGINS)

CORS_ALLOW_ALL_ORIGINS = config(
    "CORS_ALLOW_ALL_ORIGINS",
    default=not IS_PRODUCTION,
    cast=bool,
)
if IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", default=not IS_PRODUCTION, cast=bool)

CSRF_TRUSTED_ORIGINS = _csv_env(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000,https://skillbridge-eight-iota.vercel.app,https://lms-backend-eff3.onrender.com",
)
_require_production_value("CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

ROOT_URLCONF = "LMS.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "LMS.wsgi.application"
ASGI_APPLICATION = "LMS.asgi.application"



AUTH_USER_MODEL = "accounts.User"

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "EXCEPTION_HANDLER": "LMS.api.custom_exception_handler",
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=70),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# DEFAULT_FROM_EMAIL = "no-reply@lms.local"
# In settings.py (uncomment and configure)

# Email Configuration
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="mail.rijanshrestha29.com.np" if not IS_PRODUCTION else "")
EMAIL_PORT = config("EMAIL_PORT", default=465, cast=int)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=True, cast=bool)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=False, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="" if IS_PRODUCTION else "")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="" if IS_PRODUCTION else "")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)

_require_production_value("EMAIL_HOST", EMAIL_HOST)
_require_production_value("EMAIL_HOST_USER", EMAIL_HOST_USER)
_require_production_value("EMAIL_HOST_PASSWORD", EMAIL_HOST_PASSWORD)
_require_production_value("DEFAULT_FROM_EMAIL", DEFAULT_FROM_EMAIL)

# Email timeout (for slow connections)
EMAIL_TIMEOUT = 30


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB", default="lms_db" if not IS_PRODUCTION else ""),
        "USER": config("POSTGRES_USER", default="postgres" if not IS_PRODUCTION else ""),
        "PASSWORD": config("POSTGRES_PASSWORD", default=""),
        "HOST": config("POSTGRES_HOST", default="127.0.0.1" if not IS_PRODUCTION else ""),
        "PORT": config("POSTGRES_PORT", default="5432" if not IS_PRODUCTION else ""),
        "CONN_MAX_AGE": 60,  # Reuse database connections to prevent overhead
    }
}

_require_production_value("POSTGRES_DB", DATABASES["default"]["NAME"])
_require_production_value("POSTGRES_USER", DATABASES["default"]["USER"])
_require_production_value("POSTGRES_PASSWORD", DATABASES["default"]["PASSWORD"])
_require_production_value("POSTGRES_HOST", DATABASES["default"]["HOST"])
_require_production_value("POSTGRES_PORT", DATABASES["default"]["PORT"])


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kathmandu"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


JAZZMIN_SETTINGS = {
    "site_title": "LMS Admin",
    "site_header": "LMS Administration",
    "site_brand": "LMS Portal",

    "welcome_sign": "Welcome to LMS Admin Dashboard",

    "copyright": "LMS",

    "search_model": ["accounts.User", "courses.Course"],

    "user_avatar": None,

    # Top Menu
    "topmenu_links": [

        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},

        {"model": "accounts.User"},

        {"model": "courses.Course"},

        {"app": "courses"},
    ],

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Order apps/models
    "order_with_respect_to": [
        "accounts",
        "courses",
        "accounts.User",
        "courses.Course",
    ],

    # Custom Icons
    "icons": {
        "auth": "fas fa-users-cog",

        "accounts.User": "fas fa-user",

        "courses.Course": "fas fa-book",

        "courses": "fas fa-graduation-cap",
    },

    # UI Tweaks
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,

    # Sidebar style
    "sidebar_disable_expand": False,

    # Theme
    "theme": "flatly",

    # Dark mode theme
    "dark_mode_theme": "darkly",

    # Buttons
    "show_ui_builder": True,

    # Change forms
    "changeform_format": "horizontal_tabs",

    # Language chooser
    "language_chooser": False,
}

# ASGI Configuration
ASGI_APPLICATION = "LMS.asgi.application"

# Channel Layers (Redis for Docker/Production, InMemory for Local Dev)
REDIS_URL = config("REDIS_URL", default=None)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": 300,
    }
}

_require_production_value("REDIS_URL", REDIS_URL)

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

import sys
if 'runserver' in sys.argv:
    logger.debug("Using CHANNEL_LAYERS: %s", CHANNEL_LAYERS['default']['BACKEND'])


# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
CELERY_BROKER_URL = config("REDIS_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("REDIS_URL", default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"