# Generated by Django 5.1.15 on 2026-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal email - Where credentials and notifications are sent', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('ROLE_CHANGED', 'Role Changed'), ('PERMISSION_GRANTED', 'Permission Granted'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('TEMP_PASSWORD_CHANGED', 'Temporary Password Changed'), ('PROFILE_UPDATED', 'Profile Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Organization email - Used for login and all platform activities', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('tutor', 'Tutor'), ('company', 'Company'), ('student', 'Student')], db_index=True, max_length=20),
        ),
    ]
