# Generated by Django 5.1.15 on 2026-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("tutor", "Tutor"),
                    ("company", "Company"),
                    ("student", "Student"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
