# Generated by Django 5.1.15 on 2026-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this user is the platform super admin'),
        ),
    ]
