# Generated by Django 5.1.15 on 2026-05-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('accounts', '0002_user_deleted_at_user_deleted_by_user_is_deleted_and_more'),
    ]

    operations = [
    ]
