# Generated by Django 5.1.15 on 2026-05-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20260507_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_tutors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_companies',
            field=models.BooleanField(default=False),
        ),
    ]
