# Generated by Django 5.1.15 on 2026-05-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_staffpermission_can_manage_companies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpermission",
            name="can_manage_payments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffpermission",
            name="can_manage_settings",
            field=models.BooleanField(default=False),
        ),
    ]
