# Generated by Django 5.1.15 on 2026-06-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_2d3764_idx',
            old_name='notificatio_recipie_8e0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_583549_idx',
            old_name='notificatio_recipie_4a8b2a_idx',
        ),
    ]
