# Generated by Django 5.1.15 on 2026-05-04 17:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_category_course_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="preview_video_url",
        ),
        migrations.RemoveField(
            model_name="course",
            name="thumbnail_url",
        ),
        migrations.AddField(
            model_name="course",
            name="preview_video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
