# Generated by Django 5.1.15 on 2026-05-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_preview_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_scorm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="scorm_course_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
