# Generated by Django 5.1.15 on 2026-05-06 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_course_resources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentassessment',
            options={'ordering': ['-submitted_at', '-started_at'], 'verbose_name': 'Student Assessment', 'verbose_name_plural': 'Student Assessments'},
        ),
        migrations.AlterModelOptions(
            name='studentcontentprogress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentmoduleprogress',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_status_d82f31_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_instruc_680c73_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_slug_360be0_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseenrollment',
            name='course_enro_student_8023bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseenrollment',
            name='course_enro_course__37db5f_idx',
        ),
        migrations.AddField(
            model_name='assessment',
            name='allow_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='allowed_file_types',
            field=models.CharField(blank=True, help_text='Comma separated: pdf,docx,zip,mp3,mp4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='late_submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_file_size_mb',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_tab_switches',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submission_type',
            field=models.CharField(choices=[('online', 'Online (in platform)'), ('file', 'File Upload'), ('text', 'Text Entry'), ('multiple', 'Multiple Files')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='track_tab_switching',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='last_tab_switch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('auto_submitted', 'Auto Submitted (Tab Switch)')], default='started', max_length=20),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='submission_file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='scorm_course_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='scorm_import_job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='scorm_registration_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='minimum_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='course_categories',
        ),
    ]
