# Generated by Django 5.1.15 on 2026-05-06 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_certificate_options_alter_coursereview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['module__order_number', '-created_at'], 'verbose_name': 'Course Resource', 'verbose_name_plural': 'Course Resources'},
        ),
        migrations.AddField(
            model_name='courseresource',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='courses.coursemodule'),
        ),
    ]
