# Generated by Django 5.1.15 on 2026-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courseresource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecontent',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='scorm_course_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='scorm_import_job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='scorm_status',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='scorm_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('mp4', 'MP4 Video'), ('mp3', 'MP3 Audio')], max_length=20),
        ),
    ]
