# Generated by Django 5.1.15 on 2026-05-08 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_live_sessions_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='live_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.livesession'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='live_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='courses.livesession'),
        ),
    ]
