# Generated by Django 5.1.15 on 2026-05-10 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_assessment_live_session_courseresource_live_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["status", "-created_at"], name="courses_status_d82f31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["instructor", "status"], name="courses_instruc_680c73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["category"], name="courses_categor_2870c7_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["is_scorm"], name="courses_is_scor_6cc01a_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_type"], name="courses_course__f7418a_idx"
            ),
        ),
    ]
