# Generated by Django 5.1.15 on 2026-05-10 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_course_courses_status_d82f31_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["student", "status"], name="course_enro_student_8023bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["course", "status"], name="course_enro_course__37db5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(fields=["status"], name="course_enro_status_a2415a_idx"),
        ),
    ]
