# Generated by Django 5.1.15 on 2026-05-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_deleted_at_course_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('mp4', 'MP4 Video'), ('mp3', 'MP3 Audio'), ('video', 'Video'), ('text', 'Text/Article'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('link', 'External Link'), ('scorm', 'SCORM Package')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
