# Generated by Django 5.1.15 on 2026-06-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_studentassessment_feedback_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessment',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('auto_submitted', 'Auto Submitted'), ('expired', 'Expired')], default='started', max_length=20),
        ),
    ]
